### DISCUSSION TITLE
A unified config for Lupa components

### DISCUSSION THREAD

**Discussion by roybh1** [teletrace/teletrace#1166] [Ideas]
Hey all,
I am opening this discussion as follow up to this [issue](https://github.com/epsagon/lupa/issues/444)
We should decide how a user should declare Lupa's configurations in both all-in-one and distributed deployments

# Background
Currently we hold 2 separate configuration files for the [lupa-otel-collector](https://github.com/epsagon/lupa/blob/main/lupa-otelcol/config/default-config.yaml) and for the [lupa-api](https://github.com/epsagon/lupa/blob/main/pkg/config/config.go)
A basic configuration with ES as the database would introduce this duplication:

API example

```
api_port: 8080
debug: true
es_endpoints: ["http://localhost:9200"]
es_username: elastic
es_password: "123456"
es_index: lupa-traces
```

Collector example

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://localhost:9200"]
    username: elastic
    password: "123456"
    index: lupa-traces

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
```

[Jaeger](https://www.jaegertracing.io/docs/1.41/deployment/) uses an abstracted configuration to all its component (agent, collector, query, ingester etc) and prevent duplications. [SigNoz](https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/docker-compose.yaml) uses separate configurations.

I think that a good configuration:
1. Does not introduce duplications for API and Collector
2. Does not require explicitly default settings (otlp receiver, batch processor etc) 
3. Does not allow breaking configurations for Lupa operation (using Elasticsearch exporter and setting the FE to query from Sqlite)
4. Allows configuring OTEL processors, additional exporters and receivers
5. Is sharable between components in distributed deployment

# Possible Solutions
## Naive extrapolation
 Exposing OpenTelemetry collector configs and using a second document in the YAML for API configs, that will extrapolate common configs from the OTel configs 

All-In-One example
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://localhost:9200"]
    username: elastic
    password: eeee
    index: lupa-traces

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
---
api:
  apiport: 8080
  debug: true
  storage:
    elasticsearch: # will derive from exporters:elasticsearch
      maxSpans: 30
```
API-only example
```
port: 8080
debug: true
storage:
  elasticsearch:
    endpoints: ["http://localhost:9200"]
    username: elastic
    password: eeee
    index: lupa-traces

```

## Abstraction level

As @tglanz suggested:
All configurations fall into 3 buckets: Global, API, Ingestion:
* API relevant to API only; e.g
    * endpoint
    * tls
* Ingest relevant to Ingest only
    * batch size
    * retries
* Global relevant to both
    * spansStorageType
    * ElasticSearch configuration
    * SQLite configuration
    * Any other storage configuration

The API will deserialize API+Global and the Ingestion will deserialize Ingestion+Global. Meaning an all-in-one setup will receive the full configuration, an API setup will receive API+Global, Ingestion will receive Ingestion+Global.
All In One Example
```
spansStorageType: elasticsearch

ingest:
  maxBatchSize: 1Mb # memort footprint
  maxBatchCount: 5000 # spans
  retries: 3
  retriesDelay: 1s # delay between retries
  grpcReceiver:
    enabled: true
    port: 4318

api:
  port: 8080
  defaultPageSize: 100

# Can be used in AllInOne or Disaggregated modes
elasticSearch:
  endpoints:
  - somewhere.nice:9200
  spansIndex: lupa-traces
  metadataIndex: lupa-metadata # e.g for Nir's system ID
  credentials:
    user: elastic
    password: secret

```
API Example
```
spansStorageType: elasticsearch

api:
  port: 8080
  defaultPageSize: 100

# Can be used in AllInOne or Disaggregated modes
elasticSearch:
  endpoints:
  - somewhere.nice:9200
  spansIndex: lupa-traces
  metadataIndex: lupa-metadata # e.g for Nir's system ID
  credentials:
    user: elastic
    password: secret
```
And a collector alone is the same but without API and only Ingest.
It maps to code nicely too:
```
# in the Api package
type Config struct {
  spansStorageType...
  api...
  elasticsearch...
}

# in the Collector package
type ...

# in the all in one, you just deserialize both
```

Please comment other solutions we should consider and any other suggestions.
I like @tglanz's abstraction, the only downsides are not easily exposing Opentelemetry collector configs. It's more difficult to support existing exporters/receivers and processors.

@tvaintrob @tglanz @galbash @ronyis @ophiryael @haimrait @itaykat @razlo @maorlx

**Comment by tvaintrob** [comment]
@roybh1 
in general i like the abstraction that's described, few points:

1. how will the OTEL collector load this configuration?
2. how are additional processors / exporters configured?

**Reply by roybh1** [reply]
1. This is still in the air, we can generate an "internal" yaml file in the expected otel format and path or try to load the collector directly with a parsed configuration
2. I am thinking about something like this
```
spansStorageType: elasticsearch

api:
  port: 8080
  defaultPageSize: 100

# Can be used in AllInOne or Disaggregated modes
elasticSearch:
  endpoints:
  - somewhere.nice:9200
  spansIndex: lupa-traces
  metadataIndex: lupa-metadata # e.g for Nir's system ID
  credentials:
    user: elastic
    password: secret

otelProcessors: // added to the default 'batch'
  proc1:
  proc2:

otelExporters: // added to 'elasticSearch'
  otlp:
  clickhouse:
```
