### ISSUE TITLE
Helm installation fails on exporter config

### ISSUE THREAD

**Issue by chrlic** [teletrace/teletrace#1611]
When installing by Helm on K8S via
`helm install teletrace teletrace/teletrace --namespace teletrace --create-namespace`
~~~
NAME: teletrace
LAST DEPLOYED: Wed May 17 14:12:09 2023
NAMESPACE: teletrace
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
**********************************************************
 Welcome to Teletrace!
 Chart version: 0.7.0
 Teletrace version: v0.7.0
~~~

created pod fails with message:
~~~
kubectl -n teletrace logs teletrace-5849b586bb-r452m
Error: invalid configuration: no enabled exporters specified in config
{"level":"fatal","ts":1684325555.901051,"caller":"all-in-one/main.go:97","msg":"Collector stopped with an error","error":"collector server stopped with an error: invalid configuration: no enabled exporters specified in config","stacktrace":"main.startCollector\n\t/app/cmd/all-in-one/main.go:97"}
~~~

**Comment by tvaintrob** [comment]
Hey @chrlic thank you for the feedback!
It is necessary to pass the collector configuration as part of the `values` when installing the chart, i see that this is not that clearly stated in the docs or `README` so i'll make sure to fix that.

Regardless you will need to provide `values` with as least:

```yaml
collectorConfig: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
    batch:

  exporters:
    elasticsearch:
      endpoints: ["<elasticsearch-endpoint>"]
      username: "<elasticsearch-username>"
      password: "<elasticsearch-password>"
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [elasticsearch]
```

Feel free to reach out to me for further assistance!
