### ISSUE TITLE
📚️ Deploy / Support K8s Helm Chart

### ISSUE THREAD

**Issue by itaykat** [teletrace/teletrace#774]
## Problem

Currently, the deployment process of the Lupa project involves lots of friction, it requires using a dedicated k8s deployment template, and it's difficult to manage environments, configurations, versioning, and rollbacks.

## Audience

Lupa users use to manage the deployment process.

## Proposed Work

This should enable the below capabilities:

- The ability to package the platform and its dependencies into a helm chart, including any configuration settings or values that are required for it to run properly.
- The ability to store and manage these helm charts in a chart registry, such as the Helm Hub or a private chart repository.
- The ability to easily deploy the platform on a Kubernetes cluster using the helm chart and chart registry, either through a user interface or a command-line interface.
- The ability to version the helm charts and roll back to previous versions if necessary.
- Support for managing multiple environments, such as dev, staging, and production, and the ability to easily promote your application from one environment to the next.

## Incentive

Using a Helm chart improves the reliability, and stability of the deployment process, as well as makes it easier to deploy and manage versions. 

- A helm chart contains all of the information needed to deploy an application on a Kubernetes cluster.
- It includes the configuration for the application, as well as any dependencies it has and any additional components that are required for it to run.
- Helm charts allow you to version your application, making it easier to roll back to a previous version if necessary.

## Requirements and Prerequisites

- List of dependencies and prerequisites for the chart to function properly
- Detailed instructions for deploying and configuring the chart
- List of configurable options and their default values
- Examples of common usage scenarios and best practices for deployment
- List of compatible Kubernetes versions and platforms
- Documentation and support resources

## Helm Chart Structure

The main structure for a Kubernetes Helm chart includes the following files and directories:

- `Chart.yaml` - This file contains the metadata for the Helm chart, including its name, version, and description.
- `Values.yaml` - This file contains the default values for the chart's configuration options.
- `Templates` - This directory contains the Kubernetes manifest files that define the resources to be deployed. These files use the Helm templating language to access and use the values from the `Values.yaml` file.
- `Charts` - This directory can contain sub-charts, which are other Helm charts that are dependencies of this chart.
- `Tests` - This directory contains the files and scripts used to test the chart's functionality.

## Example

An example of a `chart.yaml` file:

```yaml
name: my-chart
version: 0.1.0
description: This is my Helm chart
```

An example of a `values.yaml` file:

```yaml
replicaCount: 1
image:
  repository: my-image
  tag: latest
service:
  name: my-service
  type: ClusterIP
```

A sample template file might look like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
```

## Tasks

https://github.com/epsagon/lupa/issues/774#tasklist-block-b790a398-30b4-4c59-bb38-cd9e5f463253
